In [1]:
import pandas as pd

datos = pd.read_csv('dataframe.csv',sep=',')

In [2]:
datos

,Unnamed: 0,LanguageName,Latitude,Longitude,WordModernName1,Phonetic,SpellingAltv1,source_csv
0,0,Ref. Spelling,-40.00000,-75.50000,ellos,fëjëŋɘn,feyengün,12-feyengün.csv
1,1,Santa Bárbara,-37.67405,-71.80186,ellos,ˌvë.jë.ˈŋɘn,NaN,12-feyengün.csv
2,2,Cañete,-37.96722,-73.39282,ellos,cʰɪ.ˈðwɪ.ŋɘn,NaN,12-feyengün.csv
3,3,Tirúa,-38.36990,-73.49067,ellos,ˈɸë.jë.ɣ̞ɐ̝,NaN,12-feyengün.csv
4,4,Alto Bío Bío,-38.04457,-71.36344,ellos,m̩.ˌvë.jë.ˈŋɘn,NaN,12-feyengün.csv
...,...,...,...,...,...,...,...,...
1336,1336,Huiliches,-39.63992,-71.18686,vino,pʊl.ˈkʊ,NaN,9-pulkü.csv
1337,1337,Jacobacci,-41.28813,-69.55719,vino,ɸʊl.ˈkʰʊ,NaN,9-pulkü.csv
1338,1338,Cushamen,-42.23392,-71.34994,vino,pʰʊl.ˈkʰʊ,NaN,9-pulkü.csv
1339,1339,Futaleufú,-42.95052,-71.18351,vino,ɸʊl.ˈxʊ,NaN,9-pulkü.csv
1340,1340,Lago Rosario,-43.24408,-71.32581,vino,pʊl.ˈkʊ,NaN,9-pulkü.csv

In [5]:
names = set(datos['LanguageName'])

In [6]:
names

{'Alto Bío Bío',
 'Aluminé',
 'Angol',
 'Cañete',
 'Chalileo',
 'Chol Chol',
 'Cunco',
 'Curarrehue',
 'Cushamen',
 'Dollinco',
 'Ercilla',
 'Freire',
 'Futaleufú',
 'Galvarino',
 'Huiliches',
 'Icalma',
 'Jacobacci',
 'Junín de los Andes',
 'Lago Rosario',
 'Lanco',
 'Lonquimay',
 'Lumaco',
 'Mariquina',
 'Nueva Toltén',
 'Panguipulli',
 'Picunches',
 'Puerto Saavedra',
 'Ref. Spelling',
 'S. Juan de la Costa',
 'San Pablo',
 'Santa Bárbara',
 'Tirúa',
 'Truf Truf',
 'Valdivia',
 'Victoria',
 'Vilcún',
 'Villarrica',
 'Zapala'}

In [7]:
Latitud = set(datos['Latitude'])